//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MatsiveR2msgs
{
    [Serializable]
    public class UnityCubePositionMsg : Message
    {
        public const string k_RosMessageName = "matsive_r2msgs/UnityCubePosition";
        public override string RosMessageName => k_RosMessageName;

        public double[] x;
        public double[] y;
        public double[] z;
        public double[] q1;
        public double[] q2;
        public double[] q3;

        public UnityCubePositionMsg()
        {
            this.x = new double[1];
            this.y = new double[1];
            this.z = new double[1];
            this.q1 = new double[1];
            this.q2 = new double[1];
            this.q3 = new double[1];
        }

        public UnityCubePositionMsg(double[] x, double[] y, double[] z, double[] q1, double[] q2, double[] q3)
        {
            this.x = x;
            this.y = y;
            this.z = z;
            this.q1 = q1;
            this.q2 = q2;
            this.q3 = q3;
        }

        public static UnityCubePositionMsg Deserialize(MessageDeserializer deserializer) => new UnityCubePositionMsg(deserializer);

        private UnityCubePositionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x, sizeof(double), 1);
            deserializer.Read(out this.y, sizeof(double), 1);
            deserializer.Read(out this.z, sizeof(double), 1);
            deserializer.Read(out this.q1, sizeof(double), 1);
            deserializer.Read(out this.q2, sizeof(double), 1);
            deserializer.Read(out this.q3, sizeof(double), 1);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
            serializer.Write(this.q1);
            serializer.Write(this.q2);
            serializer.Write(this.q3);
        }

        public override string ToString()
        {
            return "UnityCubePositionMsg: " +
            "\nx: " + System.String.Join(", ", x.ToList()) +
            "\ny: " + System.String.Join(", ", y.ToList()) +
            "\nz: " + System.String.Join(", ", z.ToList()) +
            "\nq1: " + System.String.Join(", ", q1.ToList()) +
            "\nq2: " + System.String.Join(", ", q2.ToList()) +
            "\nq3: " + System.String.Join(", ", q3.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
